service: pizzaslice-backend
frameworkVersion: "3"

custom:
  dotenv:
    path: .env

plugins:
  - serverless-dotenv-plugin

provider:
  name: aws
  region: ap-south-1
  stage: ${opt:stage, 'dev'}
  runtime: nodejs18.x
  memorySize: 512
  timeout: 15
  environment:
    NODE_ENV: production
    MONGO_URI: ${env:MONGO_URI}
    RAZORPAY_KEY_ID: ${env:RAZORPAY_KEY_ID}
    RAZORPAY_KEY_SECRET: ${env:RAZORPAY_KEY_SECRET}
    CLIENT_ORIGIN: ${env:CLIENT_ORIGIN, "*"}
  httpApi:
    cors: true

functions:
  api:
    handler: lambda.handler
    events:
      - httpApi:
          path: /{proxy+}
          method: ANY

package:
  patterns:
    - "!node_modules/.bin/**"
    - "!README.md"
